# Generated by Django 5.1.1 on 2026-03-18 07:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Veduci',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meno', models.CharField(max_length=64)),
                ('email', models.EmailField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Kruzok',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazov', models.CharField(max_length=100)),
                ('den', models.CharField(max_length=32)),
                ('miestnost', models.CharField(max_length=16)),
                ('veduci', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kruzky.veduci')),
            ],
        ),
    ]
